module.exports = {
   tweet_templates:['@<handle> We’re Univ of MN researchers studying how people use emoji. Do you have time for a short survey?',
                    '@<handle> We’re Univ of MN researchers studying how people use emoji. Do you have time for a quick survey?',
                    '@<handle> We’re Univ of MN researchers studying how people use emoji. Do you have time for a brief survey?',
                    '@<handle> We’re Univ of MN researchers studying how people use emoji. Could you help by taking a short survey?',
                    '@<handle> We’re Univ of MN researchers studying how people use emoji. Could you help by taking a quick survey?',
                    '@<handle> We’re Univ of MN researchers studying how people use emoji. Could you help by taking a brief survey?',
                    '@<handle> We’re Univ of MN researchers studying emoji usage. Do you have time for a short survey?',
                    '@<handle> We’re Univ of MN researchers studying emoji usage. Do you have time for a quick survey?',
                    '@<handle> We’re Univ of MN researchers studying emoji usage. Do you have time for a brief survey?',
                    '@<handle> We’re Univ of MN researchers studying emoji usage. Could you help by taking a short survey?',
                    '@<handle> We’re Univ of MN researchers studying emoji usage. Could you help by taking a quick survey?',
                    '@<handle> We’re Univ of MN researchers studying emoji usage. Could you help by taking a brief survey?',
                    '@<handle> We’re Univ of MN researchers who study emoji. Do you have time for a short survey?',
                    '@<handle> We’re Univ of MN researchers who study emoji. Do you have time for a quick survey?',
                    '@<handle> We’re Univ of MN researchers who study emoji. Do you have time for a brief survey?',
                    '@<handle> We’re Univ of MN researchers who study emoji. Could you help by taking a short survey?',
                    '@<handle> We’re Univ of MN researchers who study emoji. Could you help by taking a quick survey?',
                    '@<handle> We’re Univ of MN researchers who study emoji. Could you help by taking a brief survey?',
                    '@<handle> We’re researchers at UMN studying how people use emoji. Do you have time for a short survey?',
                    '@<handle> We’re researchers at UMN studying how people use emoji. Do you have time for a quick survey?',
                    '@<handle> We’re researchers at UMN studying how people use emoji. Do you have time for a brief survey?',
                    '@<handle> We’re researchers at UMN studying how people use emoji. Could you help by taking a short survey?',
                    '@<handle> We’re researchers at UMN studying how people use emoji. Could you help by taking a quick survey?',
                    '@<handle> We’re researchers at UMN studying how people use emoji. Could you help by taking a brief survey?',
                    '@<handle> We’re researchers at UMN studying emoji usage. Do you have time for a short survey?',
                    '@<handle> We’re researchers at UMN studying emoji usage. Do you have time for a quick survey?',
                    '@<handle> We’re researchers at UMN studying emoji usage. Do you have time for a brief survey?',
                    '@<handle> We’re researchers at UMN studying emoji usage. Could you help by taking a short survey?',
                    '@<handle> We’re researchers at UMN studying emoji usage. Could you help by taking a quick survey?',
                    '@<handle> We’re researchers at UMN studying emoji usage. Could you help by taking a brief survey?',
                    '@<handle> We’re researchers at UMN who study emoji. Do you have time for a short survey?',
                    '@<handle> We’re researchers at UMN who study emoji. Do you have time for a quick survey?',
                    '@<handle> We’re researchers at UMN who study emoji. Do you have time for a brief survey?',
                    '@<handle> We’re researchers at UMN who study emoji. Could you help by taking a short survey?',
                    '@<handle> We’re researchers at UMN who study emoji. Could you help by taking a quick survey?',
                    '@<handle> We’re researchers at UMN who study emoji. Could you help by taking a brief survey?',
                    '@<handle> We study emoji at the Univ of MN and we noticed you just tweeted one. Have time for a short survey?',
                    '@<handle> We study emoji at the Univ of MN and we noticed you just tweeted one. Have time for a quick survey?',
                    '@<handle> We study emoji at the Univ of MN and we noticed you just tweeted one. Have time for a brief survey?',
                    '@<handle> We study emoji at the Univ of MN and we noticed you just tweeted one. Help us via a short survey?',
                    '@<handle> We study emoji at the Univ of MN and we noticed you just tweeted one. Help us via a quick survey?',
                    '@<handle> We study emoji at the Univ of MN and we noticed you just tweeted one. Help us via a brief survey?',
                    '@<handle> We study emoji at UMN and we noticed you just tweeted one. Do you have time for a short survey?',
                    '@<handle> We study emoji at UMN and we noticed you just tweeted one. Do you have time for a quick survey?',
                    '@<handle> We study emoji at UMN and we noticed you just tweeted one. Do you have time for a brief survey?',
                    '@<handle> We study emoji at UMN and we noticed you just tweeted one. Could you help by taking a short survey?',
                    '@<handle> We study emoji at UMN and we noticed you just tweeted one. Could you help by taking a quick survey?',
                    '@<handle> We study emoji at UMN and we noticed you just tweeted one. Could you help by taking a brief survey?',
                    '@<handle> We’re computer scientists at UMN studying how people use emoji. Do you have time for a short survey?',
                    '@<handle> We’re computer scientists at UMN studying how people use emoji. Do you have time for a quick survey?',
                    '@<handle> We’re computer scientists at UMN studying how people use emoji. Do you have time for a brief survey?',
                    '@<handle> We’re computer scientists at UMN studying how people use emoji. Help us via a short survey?',
                    '@<handle> We’re computer scientists at UMN studying how people use emoji. Help us via a quick survey?',
                    '@<handle> We’re computer scientists at UMN studying how people use emoji. Help us via a brief survey?',
                    '@<handle> We’re computer scientists at UMN studying emoji usage. Do you have time for a short survey?',
                    '@<handle> We’re computer scientists at UMN studying emoji usage. Do you have time for a quick survey?',
                    '@<handle> We’re computer scientists at UMN studying emoji usage. Do you have time for a brief survey?',
                    '@<handle> We’re computer scientists at UMN studying emoji usage. Could you help by taking a short survey?',
                    '@<handle> We’re computer scientists at UMN studying emoji usage. Could you help by taking a quick survey?',
                    '@<handle> We’re computer scientists at UMN studying emoji usage. Could you help by taking a brief survey?',
                    '@<handle> We’re computer scientists at UMN who study emoji. Do you have time for a short survey?',
                    '@<handle> We’re computer scientists at UMN who study emoji. Do you have time for a quick survey?',
                    '@<handle> We’re computer scientists at UMN who study emoji. Do you have time for a brief survey?',
                    '@<handle> We’re computer scientists at UMN who study emoji. Could you help by taking a short survey?',
                    '@<handle> We’re computer scientists at UMN who study emoji. Could you help by taking a quick survey?',
                    '@<handle> We’re computer scientists at UMN who study emoji. Could you help by taking a brief survey?',
                    'Hi @<handle>, We’re Univ of MN researchers studying how people use emoji. Do you have time for a short survey?',
                    'Hi @<handle>, We’re Univ of MN researchers studying how people use emoji. Do you have time for a quick survey?',
                    'Hi @<handle>, We’re Univ of MN researchers studying how people use emoji. Do you have time for a brief survey?',
                    'Hi @<handle>, We’re Univ of MN researchers studying how people use emoji. Help us via a short survey?',
                    'Hi @<handle>, We’re Univ of MN researchers studying how people use emoji. Help us via a quick survey?',
                    'Hi @<handle>, We’re Univ of MN researchers studying how people use emoji. Help us via a brief survey?',
                    'Hi @<handle>, We’re Univ of MN researchers studying emoji usage. Do you have time for a short survey?',
                    'Hi @<handle>, We’re Univ of MN researchers studying emoji usage. Do you have time for a quick survey?',
                    'Hi @<handle>, We’re Univ of MN researchers studying emoji usage. Do you have time for a brief survey?',
                    'Hi @<handle>, We’re Univ of MN researchers studying emoji usage. Could you help by taking a short survey?',
                    'Hi @<handle>, We’re Univ of MN researchers studying emoji usage. Could you help by taking a quick survey?',
                    'Hi @<handle>, We’re Univ of MN researchers studying emoji usage. Could you help by taking a brief survey?',
                    'Hi @<handle>, We’re Univ of MN researchers who study emoji. Do you have time for a short survey?',
                    'Hi @<handle>, We’re Univ of MN researchers who study emoji. Do you have time for a quick survey?',
                    'Hi @<handle>, We’re Univ of MN researchers who study emoji. Do you have time for a brief survey?',
                    'Hi @<handle>, We’re Univ of MN researchers who study emoji. Could you help by taking a short survey?',
                    'Hi @<handle>, We’re Univ of MN researchers who study emoji. Could you help by taking a quick survey?',
                    'Hi @<handle>, We’re Univ of MN researchers who study emoji. Could you help by taking a brief survey?',
                    'Hi @<handle>, We’re researchers at UMN studying how people use emoji. Do you have time for a short survey?',
                    'Hi @<handle>, We’re researchers at UMN studying how people use emoji. Do you have time for a quick survey?',
                    'Hi @<handle>, We’re researchers at UMN studying how people use emoji. Do you have time for a brief survey?',
                    'Hi @<handle>, We’re researchers at UMN studying how people use emoji. Could you help by taking a short survey?',
                    'Hi @<handle>, We’re researchers at UMN studying how people use emoji. Could you help by taking a quick survey?',
                    'Hi @<handle>, We’re researchers at UMN studying how people use emoji. Could you help by taking a brief survey?',
                    'Hi @<handle>, We’re researchers at UMN studying emoji usage. Do you have time for a short survey?',
                    'Hi @<handle>, We’re researchers at UMN studying emoji usage. Do you have time for a quick survey?',
                    'Hi @<handle>, We’re researchers at UMN studying emoji usage. Do you have time for a brief survey?',
                    'Hi @<handle>, We’re researchers at UMN studying emoji usage. Could you help by taking a short survey?',
                    'Hi @<handle>, We’re researchers at UMN studying emoji usage. Could you help by taking a quick survey?',
                    'Hi @<handle>, We’re researchers at UMN studying emoji usage. Could you help by taking a brief survey?',
                    'Hi @<handle>, We’re researchers at UMN who study emoji. Do you have time for a short survey?',
                    'Hi @<handle>, We’re researchers at UMN who study emoji. Do you have time for a quick survey?',
                    'Hi @<handle>, We’re researchers at UMN who study emoji. Do you have time for a brief survey?',
                    'Hi @<handle>, We’re researchers at UMN who study emoji. Could you help by taking a short survey?',
                    'Hi @<handle>, We’re researchers at UMN who study emoji. Could you help by taking a quick survey?',
                    'Hi @<handle>, We’re researchers at UMN who study emoji. Could you help by taking a brief survey?',
                    'Hi @<handle>, We study emoji at the Univ of MN and we noticed you just tweeted one. Time for a short survey?',
                    'Hi @<handle>, We study emoji at the Univ of MN and we noticed you just tweeted one. Time for a quick survey?',
                    'Hi @<handle>, We study emoji at the Univ of MN and we noticed you just tweeted one. Time for a brief survey?',
                    'Hi @<handle>, We study emoji at UMN and we noticed you just tweeted one. Do you have time for a short survey?',
                    'Hi @<handle>, We study emoji at UMN and we noticed you just tweeted one. Do you have time for a quick survey?',
                    'Hi @<handle>, We study emoji at UMN and we noticed you just tweeted one. Do you have time for a brief survey?',
                    'Hi @<handle>, We study emoji at UMN and we noticed you just tweeted one. Help us via a short survey?',
                    'Hi @<handle>, We study emoji at UMN and we noticed you just tweeted one. Help us via a quick survey?',
                    'Hi @<handle>, We study emoji at UMN and we noticed you just tweeted one. Help us via a brief survey?',
                    'Hi @<handle>, We’re computer scientists at UMN studying how people use emoji. Have time for a short survey?',
                    'Hi @<handle>, We’re computer scientists at UMN studying how people use emoji. Have time for a quick survey?',
                    'Hi @<handle>, We’re computer scientists at UMN studying how people use emoji. Have time for a brief survey?',
                    'Hi @<handle>, We’re computer scientists at UMN studying how people use emoji. Help us via a short survey?',
                    'Hi @<handle>, We’re computer scientists at UMN studying how people use emoji. Help us via a quick survey?',
                    'Hi @<handle>, We’re computer scientists at UMN studying how people use emoji. Help us via a brief survey?',
                    'Hi @<handle>, We’re computer scientists at UMN studying emoji usage. Do you have time for a short survey?',
                    'Hi @<handle>, We’re computer scientists at UMN studying emoji usage. Do you have time for a quick survey?',
                    'Hi @<handle>, We’re computer scientists at UMN studying emoji usage. Do you have time for a brief survey?',
                    'Hi @<handle>, We’re computer scientists at UMN studying emoji usage. Could you help by taking a short survey?',
                    'Hi @<handle>, We’re computer scientists at UMN studying emoji usage. Could you help by taking a quick survey?',
                    'Hi @<handle>, We’re computer scientists at UMN studying emoji usage. Could you help by taking a brief survey?',
                    'Hi @<handle>, We’re computer scientists at UMN who study emoji. Do you have time for a short survey?',
                    'Hi @<handle>, We’re computer scientists at UMN who study emoji. Do you have time for a quick survey?',
                    'Hi @<handle>, We’re computer scientists at UMN who study emoji. Do you have time for a brief survey?',
                    'Hi @<handle>, We’re computer scientists at UMN who study emoji. Could you help by taking a short survey?',
                    'Hi @<handle>, We’re computer scientists at UMN who study emoji. Could you help by taking a quick survey?',
                    'Hi @<handle>, We’re computer scientists at UMN who study emoji. Could you help by taking a brief survey?',
                    '@<handle> Hi, We’re Univ of MN researchers studying how people use emoji. Do you have time for a short survey?',
                    '@<handle> Hi, We’re Univ of MN researchers studying how people use emoji. Do you have time for a quick survey?',
                    '@<handle> Hi, We’re Univ of MN researchers studying how people use emoji. Do you have time for a brief survey?',
                    '@<handle> Hi, We’re Univ of MN researchers studying how people use emoji. Help us via a short survey?',
                    '@<handle> Hi, We’re Univ of MN researchers studying how people use emoji. Help us via a quick survey?',
                    '@<handle> Hi, We’re Univ of MN researchers studying how people use emoji. Help us via a brief survey?',
                    '@<handle> Hi, We’re Univ of MN researchers studying emoji usage. Do you have time for a short survey?',
                    '@<handle> Hi, We’re Univ of MN researchers studying emoji usage. Do you have time for a quick survey?',
                    '@<handle> Hi, We’re Univ of MN researchers studying emoji usage. Do you have time for a brief survey?',
                    '@<handle> Hi, We’re Univ of MN researchers studying emoji usage. Could you help by taking a short survey?',
                    '@<handle> Hi, We’re Univ of MN researchers studying emoji usage. Could you help by taking a quick survey?',
                    '@<handle> Hi, We’re Univ of MN researchers studying emoji usage. Could you help by taking a brief survey?',
                    '@<handle> Hi, We’re Univ of MN researchers who study emoji. Do you have time for a short survey?',
                    '@<handle> Hi, We’re Univ of MN researchers who study emoji. Do you have time for a quick survey?',
                    '@<handle> Hi, We’re Univ of MN researchers who study emoji. Do you have time for a brief survey?',
                    '@<handle> Hi, We’re Univ of MN researchers who study emoji. Could you help by taking a short survey?',
                    '@<handle> Hi, We’re Univ of MN researchers who study emoji. Could you help by taking a quick survey?',
                    '@<handle> Hi, We’re Univ of MN researchers who study emoji. Could you help by taking a brief survey?',
                    '@<handle> Hi, We’re researchers at UMN studying how people use emoji. Do you have time for a short survey?',
                    '@<handle> Hi, We’re researchers at UMN studying how people use emoji. Do you have time for a quick survey?',
                    '@<handle> Hi, We’re researchers at UMN studying how people use emoji. Do you have time for a brief survey?',
                    '@<handle> Hi, We’re researchers at UMN studying how people use emoji. Could you help by taking a short survey?',
                    '@<handle> Hi, We’re researchers at UMN studying how people use emoji. Could you help by taking a quick survey?',
                    '@<handle> Hi, We’re researchers at UMN studying how people use emoji. Could you help by taking a brief survey?',
                    '@<handle> Hi, We’re researchers at UMN studying emoji usage. Do you have time for a short survey?',
                    '@<handle> Hi, We’re researchers at UMN studying emoji usage. Do you have time for a quick survey?',
                    '@<handle> Hi, We’re researchers at UMN studying emoji usage. Do you have time for a brief survey?',
                    '@<handle> Hi, We’re researchers at UMN studying emoji usage. Could you help by taking a short survey?',
                    '@<handle> Hi, We’re researchers at UMN studying emoji usage. Could you help by taking a quick survey?',
                    '@<handle> Hi, We’re researchers at UMN studying emoji usage. Could you help by taking a brief survey?',
                    '@<handle> Hi, We’re researchers at UMN who study emoji. Do you have time for a short survey?',
                    '@<handle> Hi, We’re researchers at UMN who study emoji. Do you have time for a quick survey?',
                    '@<handle> Hi, We’re researchers at UMN who study emoji. Do you have time for a brief survey?',
                    '@<handle> Hi, We’re researchers at UMN who study emoji. Could you help by taking a short survey?',
                    '@<handle> Hi, We’re researchers at UMN who study emoji. Could you help by taking a quick survey?',
                    '@<handle> Hi, We’re researchers at UMN who study emoji. Could you help by taking a brief survey?',
                    '@<handle> Hi, We study emoji at the Univ of MN and we noticed you just tweeted one. Time for a short survey?',
                    '@<handle> Hi, We study emoji at the Univ of MN and we noticed you just tweeted one. Time for a quick survey?',
                    '@<handle> Hi, We study emoji at the Univ of MN and we noticed you just tweeted one. Time for a brief survey?',
                    '@<handle> Hi, We study emoji at UMN and we noticed you just tweeted one. Do you have time for a short survey?',
                    '@<handle> Hi, We study emoji at UMN and we noticed you just tweeted one. Do you have time for a quick survey?',
                    '@<handle> Hi, We study emoji at UMN and we noticed you just tweeted one. Do you have time for a brief survey?',
                    '@<handle> Hi, We study emoji at UMN and we noticed you just tweeted one. Help us via a short survey?',
                    '@<handle> Hi, We study emoji at UMN and we noticed you just tweeted one. Help us via a quick survey?',
                    '@<handle> Hi, We study emoji at UMN and we noticed you just tweeted one. Help us via a brief survey?',
                    '@<handle> Hi, We’re computer scientists at UMN studying how people use emoji. Have time for a short survey?',
                    '@<handle> Hi, We’re computer scientists at UMN studying how people use emoji. Have time for a quick survey?',
                    '@<handle> Hi, We’re computer scientists at UMN studying how people use emoji. Have time for a brief survey?',
                    '@<handle> Hi, We’re computer scientists at UMN studying how people use emoji. Help us via a short survey?',
                    '@<handle> Hi, We’re computer scientists at UMN studying how people use emoji. Help us via a quick survey?',
                    '@<handle> Hi, We’re computer scientists at UMN studying how people use emoji. Help us via a brief survey?',
                    '@<handle> Hi, We’re computer scientists at UMN studying emoji usage. Do you have time for a short survey?',
                    '@<handle> Hi, We’re computer scientists at UMN studying emoji usage. Do you have time for a quick survey?',
                    '@<handle> Hi, We’re computer scientists at UMN studying emoji usage. Do you have time for a brief survey?',
                    '@<handle> Hi, We’re computer scientists at UMN studying emoji usage. Could you help by taking a short survey?',
                    '@<handle> Hi, We’re computer scientists at UMN studying emoji usage. Could you help by taking a quick survey?',
                    '@<handle> Hi, We’re computer scientists at UMN studying emoji usage. Could you help by taking a brief survey?',
                    '@<handle> Hi, We’re computer scientists at UMN who study emoji. Do you have time for a short survey?',
                    '@<handle> Hi, We’re computer scientists at UMN who study emoji. Do you have time for a quick survey?',
                    '@<handle> Hi, We’re computer scientists at UMN who study emoji. Do you have time for a brief survey?',
                    '@<handle> Hi, We’re computer scientists at UMN who study emoji. Could you help by taking a short survey?',
                    '@<handle> Hi, We’re computer scientists at UMN who study emoji. Could you help by taking a quick survey?',
                    '@<handle> Hi, We’re computer scientists at UMN who study emoji. Could you help by taking a brief survey?',
                    'Hi @<handle>! We’re Univ of MN researchers studying how people use emoji. Do you have time for a short survey?',
                    'Hi @<handle>! We’re Univ of MN researchers studying how people use emoji. Do you have time for a quick survey?',
                    'Hi @<handle>! We’re Univ of MN researchers studying how people use emoji. Do you have time for a brief survey?',
                    'Hi @<handle>! We’re Univ of MN researchers studying how people use emoji. Help us via a short survey?',
                    'Hi @<handle>! We’re Univ of MN researchers studying how people use emoji. Help us via a quick survey?',
                    'Hi @<handle>! We’re Univ of MN researchers studying how people use emoji. Help us via a brief survey?',
                    'Hi @<handle>! We’re Univ of MN researchers studying emoji usage. Do you have time for a short survey?',
                    'Hi @<handle>! We’re Univ of MN researchers studying emoji usage. Do you have time for a quick survey?',
                    'Hi @<handle>! We’re Univ of MN researchers studying emoji usage. Do you have time for a brief survey?',
                    'Hi @<handle>! We’re Univ of MN researchers studying emoji usage. Could you help by taking a short survey?',
                    'Hi @<handle>! We’re Univ of MN researchers studying emoji usage. Could you help by taking a quick survey?',
                    'Hi @<handle>! We’re Univ of MN researchers studying emoji usage. Could you help by taking a brief survey?',
                    'Hi @<handle>! We’re Univ of MN researchers who study emoji. Do you have time for a short survey?',
                    'Hi @<handle>! We’re Univ of MN researchers who study emoji. Do you have time for a quick survey?',
                    'Hi @<handle>! We’re Univ of MN researchers who study emoji. Do you have time for a brief survey?',
                    'Hi @<handle>! We’re Univ of MN researchers who study emoji. Could you help by taking a short survey?',
                    'Hi @<handle>! We’re Univ of MN researchers who study emoji. Could you help by taking a quick survey?',
                    'Hi @<handle>! We’re Univ of MN researchers who study emoji. Could you help by taking a brief survey?',
                    'Hi @<handle>! We’re researchers at UMN studying how people use emoji. Do you have time for a short survey?',
                    'Hi @<handle>! We’re researchers at UMN studying how people use emoji. Do you have time for a quick survey?',
                    'Hi @<handle>! We’re researchers at UMN studying how people use emoji. Do you have time for a brief survey?',
                    'Hi @<handle>! We’re researchers at UMN studying how people use emoji. Could you help by taking a short survey?',
                    'Hi @<handle>! We’re researchers at UMN studying how people use emoji. Could you help by taking a quick survey?',
                    'Hi @<handle>! We’re researchers at UMN studying how people use emoji. Could you help by taking a brief survey?',
                    'Hi @<handle>! We’re researchers at UMN studying emoji usage. Do you have time for a short survey?',
                    'Hi @<handle>! We’re researchers at UMN studying emoji usage. Do you have time for a quick survey?',
                    'Hi @<handle>! We’re researchers at UMN studying emoji usage. Do you have time for a brief survey?',
                    'Hi @<handle>! We’re researchers at UMN studying emoji usage. Could you help by taking a short survey?',
                    'Hi @<handle>! We’re researchers at UMN studying emoji usage. Could you help by taking a quick survey?',
                    'Hi @<handle>! We’re researchers at UMN studying emoji usage. Could you help by taking a brief survey?',
                    'Hi @<handle>! We’re researchers at UMN who study emoji. Do you have time for a short survey?',
                    'Hi @<handle>! We’re researchers at UMN who study emoji. Do you have time for a quick survey?',
                    'Hi @<handle>! We’re researchers at UMN who study emoji. Do you have time for a brief survey?',
                    'Hi @<handle>! We’re researchers at UMN who study emoji. Could you help by taking a short survey?',
                    'Hi @<handle>! We’re researchers at UMN who study emoji. Could you help by taking a quick survey?',
                    'Hi @<handle>! We’re researchers at UMN who study emoji. Could you help by taking a brief survey?',
                    'Hi @<handle>! We study emoji at the Univ of MN and we noticed you just tweeted one. Time for a short survey?',
                    'Hi @<handle>! We study emoji at the Univ of MN and we noticed you just tweeted one. Time for a quick survey?',
                    'Hi @<handle>! We study emoji at the Univ of MN and we noticed you just tweeted one. Time for a brief survey?',
                    'Hi @<handle>! We study emoji at UMN and we noticed you just tweeted one. Do you have time for a short survey?',
                    'Hi @<handle>! We study emoji at UMN and we noticed you just tweeted one. Do you have time for a quick survey?',
                    'Hi @<handle>! We study emoji at UMN and we noticed you just tweeted one. Do you have time for a brief survey?',
                    'Hi @<handle>! We study emoji at UMN and we noticed you just tweeted one. Help us via a short survey?',
                    'Hi @<handle>! We study emoji at UMN and we noticed you just tweeted one. Help us via a quick survey?',
                    'Hi @<handle>! We study emoji at UMN and we noticed you just tweeted one. Help us via a brief survey?',
                    'Hi @<handle>! We’re computer scientists at UMN studying how people use emoji. Have time for a short survey?',
                    'Hi @<handle>! We’re computer scientists at UMN studying how people use emoji. Have time for a quick survey?',
                    'Hi @<handle>! We’re computer scientists at UMN studying how people use emoji. Have time for a brief survey?',
                    'Hi @<handle>! We’re computer scientists at UMN studying how people use emoji. Help us via a short survey?',
                    'Hi @<handle>! We’re computer scientists at UMN studying how people use emoji. Help us via a quick survey?',
                    'Hi @<handle>! We’re computer scientists at UMN studying how people use emoji. Help us via a brief survey?',
                    'Hi @<handle>! We’re computer scientists at UMN studying emoji usage. Do you have time for a short survey?',
                    'Hi @<handle>! We’re computer scientists at UMN studying emoji usage. Do you have time for a quick survey?',
                    'Hi @<handle>! We’re computer scientists at UMN studying emoji usage. Do you have time for a brief survey?',
                    'Hi @<handle>! We’re computer scientists at UMN studying emoji usage. Could you help by taking a short survey?',
                    'Hi @<handle>! We’re computer scientists at UMN studying emoji usage. Could you help by taking a quick survey?',
                    'Hi @<handle>! We’re computer scientists at UMN studying emoji usage. Could you help by taking a brief survey?',
                    'Hi @<handle>! We’re computer scientists at UMN who study emoji. Do you have time for a short survey?',
                    'Hi @<handle>! We’re computer scientists at UMN who study emoji. Do you have time for a quick survey?',
                    'Hi @<handle>! We’re computer scientists at UMN who study emoji. Do you have time for a brief survey?',
                    'Hi @<handle>! We’re computer scientists at UMN who study emoji. Could you help by taking a short survey?',
                    'Hi @<handle>! We’re computer scientists at UMN who study emoji. Could you help by taking a quick survey?',
                    'Hi @<handle>! We’re computer scientists at UMN who study emoji. Could you help by taking a brief survey?',
                    '@<handle> Hi! We’re Univ of MN researchers studying how people use emoji. Do you have time for a short survey?',
                    '@<handle> Hi! We’re Univ of MN researchers studying how people use emoji. Do you have time for a quick survey?',
                    '@<handle> Hi! We’re Univ of MN researchers studying how people use emoji. Do you have time for a brief survey?',
                    '@<handle> Hi! We’re Univ of MN researchers studying how people use emoji. Help us via a short survey?',
                    '@<handle> Hi! We’re Univ of MN researchers studying how people use emoji. Help us via a quick survey?',
                    '@<handle> Hi! We’re Univ of MN researchers studying how people use emoji. Help us via a brief survey?',
                    '@<handle> Hi! We’re Univ of MN researchers studying emoji usage. Do you have time for a short survey?',
                    '@<handle> Hi! We’re Univ of MN researchers studying emoji usage. Do you have time for a quick survey?',
                    '@<handle> Hi! We’re Univ of MN researchers studying emoji usage. Do you have time for a brief survey?',
                    '@<handle> Hi! We’re Univ of MN researchers studying emoji usage. Could you help by taking a short survey?',
                    '@<handle> Hi! We’re Univ of MN researchers studying emoji usage. Could you help by taking a quick survey?',
                    '@<handle> Hi! We’re Univ of MN researchers studying emoji usage. Could you help by taking a brief survey?',
                    '@<handle> Hi! We’re Univ of MN researchers who study emoji. Do you have time for a short survey?',
                    '@<handle> Hi! We’re Univ of MN researchers who study emoji. Do you have time for a quick survey?',
                    '@<handle> Hi! We’re Univ of MN researchers who study emoji. Do you have time for a brief survey?',
                    '@<handle> Hi! We’re Univ of MN researchers who study emoji. Could you help by taking a short survey?',
                    '@<handle> Hi! We’re Univ of MN researchers who study emoji. Could you help by taking a quick survey?',
                    '@<handle> Hi! We’re Univ of MN researchers who study emoji. Could you help by taking a brief survey?',
                    '@<handle> Hi! We’re researchers at UMN studying how people use emoji. Do you have time for a short survey?',
                    '@<handle> Hi! We’re researchers at UMN studying how people use emoji. Do you have time for a quick survey?',
                    '@<handle> Hi! We’re researchers at UMN studying how people use emoji. Do you have time for a brief survey?',
                    '@<handle> Hi! We’re researchers at UMN studying how people use emoji. Could you help by taking a short survey?',
                    '@<handle> Hi! We’re researchers at UMN studying how people use emoji. Could you help by taking a quick survey?',
                    '@<handle> Hi! We’re researchers at UMN studying how people use emoji. Could you help by taking a brief survey?',
                    '@<handle> Hi! We’re researchers at UMN studying emoji usage. Do you have time for a short survey?',
                    '@<handle> Hi! We’re researchers at UMN studying emoji usage. Do you have time for a quick survey?',
                    '@<handle> Hi! We’re researchers at UMN studying emoji usage. Do you have time for a brief survey?',
                    '@<handle> Hi! We’re researchers at UMN studying emoji usage. Could you help by taking a short survey?',
                    '@<handle> Hi! We’re researchers at UMN studying emoji usage. Could you help by taking a quick survey?',
                    '@<handle> Hi! We’re researchers at UMN studying emoji usage. Could you help by taking a brief survey?',
                    '@<handle> Hi! We’re researchers at UMN who study emoji. Do you have time for a short survey?',
                    '@<handle> Hi! We’re researchers at UMN who study emoji. Do you have time for a quick survey?',
                    '@<handle> Hi! We’re researchers at UMN who study emoji. Do you have time for a brief survey?',
                    '@<handle> Hi! We’re researchers at UMN who study emoji. Could you help by taking a short survey?',
                    '@<handle> Hi! We’re researchers at UMN who study emoji. Could you help by taking a quick survey?',
                    '@<handle> Hi! We’re researchers at UMN who study emoji. Could you help by taking a brief survey?',
                    '@<handle> Hi! We study emoji at the Univ of MN and we noticed you just tweeted one. Time for a short survey?',
                    '@<handle> Hi! We study emoji at the Univ of MN and we noticed you just tweeted one. Time for a quick survey?',
                    '@<handle> Hi! We study emoji at the Univ of MN and we noticed you just tweeted one. Time for a brief survey?',
                    '@<handle> Hi! We study emoji at UMN and we noticed you just tweeted one. Do you have time for a short survey?',
                    '@<handle> Hi! We study emoji at UMN and we noticed you just tweeted one. Do you have time for a quick survey?',
                    '@<handle> Hi! We study emoji at UMN and we noticed you just tweeted one. Do you have time for a brief survey?',
                    '@<handle> Hi! We study emoji at UMN and we noticed you just tweeted one. Help us via a short survey?',
                    '@<handle> Hi! We study emoji at UMN and we noticed you just tweeted one. Help us via a quick survey?',
                    '@<handle> Hi! We study emoji at UMN and we noticed you just tweeted one. Help us via a brief survey?',
                    '@<handle> Hi! We’re computer scientists at UMN studying how people use emoji. Have time for a short survey?',
                    '@<handle> Hi! We’re computer scientists at UMN studying how people use emoji. Have time for a quick survey?',
                    '@<handle> Hi! We’re computer scientists at UMN studying how people use emoji. Have time for a brief survey?',
                    '@<handle> Hi! We’re computer scientists at UMN studying how people use emoji. Help us via a short survey?',
                    '@<handle> Hi! We’re computer scientists at UMN studying how people use emoji. Help us via a quick survey?',
                    '@<handle> Hi! We’re computer scientists at UMN studying how people use emoji. Help us via a brief survey?',
                    '@<handle> Hi! We’re computer scientists at UMN studying emoji usage. Do you have time for a short survey?',
                    '@<handle> Hi! We’re computer scientists at UMN studying emoji usage. Do you have time for a quick survey?',
                    '@<handle> Hi! We’re computer scientists at UMN studying emoji usage. Do you have time for a brief survey?',
                    '@<handle> Hi! We’re computer scientists at UMN studying emoji usage. Could you help by taking a short survey?',
                    '@<handle> Hi! We’re computer scientists at UMN studying emoji usage. Could you help by taking a quick survey?',
                    '@<handle> Hi! We’re computer scientists at UMN studying emoji usage. Could you help by taking a brief survey?',
                    '@<handle> Hi! We’re computer scientists at UMN who study emoji. Do you have time for a short survey?',
                    '@<handle> Hi! We’re computer scientists at UMN who study emoji. Do you have time for a quick survey?',
                    '@<handle> Hi! We’re computer scientists at UMN who study emoji. Do you have time for a brief survey?',
                    '@<handle> Hi! We’re computer scientists at UMN who study emoji. Could you help by taking a short survey?',
                    '@<handle> Hi! We’re computer scientists at UMN who study emoji. Could you help by taking a quick survey?',
                    '@<handle> Hi! We’re computer scientists at UMN who study emoji. Could you help by taking a brief survey?']
}